<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows10.0.22000.0</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="LiveCharts.WinForms" Version="0.9.7.1" />
    <PackageReference Include="LiveChartsCore" Version="2.0.0" />
    <PackageReference Include="LiveChartsCore.SkiaSharpView.WinForms" Version="2.0.0" />
    <PackageReference Include="Oracle.ManagedDataAccess.Core" Version="23.26.100" />
    <PackageReference Include="SkiaSharp.NativeAssets.Win32" Version="3.119.2" />
  </ItemGroup>

</Project>