INSERT INTO GENRES (GENRECODE,GENREDESC)
VALUES ('HR','HORROR');

INSERT INTO GENRES (GENRECODE,GENREDESC)
VALUES ('FN','FANTASY');

INSERT INTO GENRES (GENRECODE,GENREDESC)
VALUES ('SF','SCIENCE FICTION');

INSERT INTO GENRES (GENRECODE,GENREDESC)
VALUES ('MY','MYSTERY');

INSERT INTO GENRES (GENRECODE,GENREDESC)
VALUES ('RM','ROMANCE');

INSERT INTO GENRES (GENRECODE,GENREDESC)
VALUES ('TH','THRILLER');

INSERT INTO GENRES (GENRECODE,GENREDESC)
VALUES ('BI','BIOGRAPHY');

INSERT INTO GENRES (GENRECODE,GENREDESC)
VALUES ('HI','HISTORY');

INSERT INTO GENRES (GENRECODE,GENREDESC)
VALUES ('AD','ADVENTURE');
COMMIT;


