
DROP TABLE FINES;
DROP TABLE LOANS;
DROP TABLE MEMBERS;
DROP TABLE BOOKS;
DROP TABLE GENRES;


CREATE TABLE GENRES(
GenreCode CHAR(2),
GenreDesc VARCHAR(30) NOT NULL,
CONSTRAINT pk_genres PRIMARY KEY (GenreCode)
);
COMMIT;

CREATE TABLE BOOKS (
BookID NUMBER,
GenreCode CHAR(2),
BookTitle VARCHAR(50) NOT NULL,
Author VARCHAR(30) NOT NULL,
Description VARCHAR(50) NOT NULL,
Status CHAR(1) DEFAULT 'A',
IsDeleted CHAR(1) DEFAULT 'N',
CONSTRAINT uq_book UNIQUE(BookTitle,Author),
CONSTRAINT pk_books PRIMARY KEY (BookID),
CONSTRAINT fk_genre FOREIGN KEY (GenreCode) REFERENCES Genres(GenreCode)
);
COMMIT;

CREATE TABLE MEMBERS(
MemID NUMBER,
Fname Varchar(25) NOT NULL,
Sname VARCHAR(25) NOT NULL,
Phone VARCHAR(13) NOT NULL,
Email VARCHAR(50) NOT NULL,
IsDeleted CHAR(1) DEFAULT 'N',
CONSTRAINT uq_member UNIQUE(Email),
CONSTRAINT pk_Members PRIMARY KEY(MemID)
);
COMMIT;

CREATE TABLE LOANS(
LoanID NUMBER,
MemID NUMBER,
BookID NUMBER,
StartDate DATE NOT NULL,
DueDate DATE NOT NULL,
ReturnedDate DATE DEFAULT NULL,
CONSTRAINT pk_Loans PRIMARY KEY(LoanID),
CONSTRAINT fk_MemID FOREIGN KEY(MemID) REFERENCES Members(MemID),
CONSTRAINT fk_BookID FOREIGN KEY(BookID) REFERENCES Books(BookID)
);
COMMIT;

CREATE TABLE FINES(
FineID NUMBER,
LoanID NUMBER,
Amount DECIMAL(4,2) NOT NULL,
FineDate DATE NOT NULL,
CONSTRAINT pk_Fines PRIMARY KEY(FineID),
CONSTRAINT fk_LoanID FOREIGN KEY(LoanID) REFERENCES Loans(LoanID)
);
COMMIT;



